### ISSUE TITLE
Cannot verify data

### ISSUE THREAD

**Issue by bosmadev** [amxDusT/CookieBan-amxx#1]
Kicked from server with “Cannot verify data”

-Using full_system
-SQL connection is ok
-All ssl certs and redirects are removed. http://dexzombie.ml/dexbanning_check.php (prints text in body, so php is loaded)
-SQL tables exist and are empty.
-Using ReUnion

**Comment by amxDusT** [comment]
Hi, sorry for the late response. Let me know if you still need help with it over steam possibly. 

As for your problem, check that the table inside the .php is the same table as the .sma.
